# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0002_auto_20190808_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='selected_column',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
