# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0003_indicatorprofile_selected_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='selected_column',
            new_name='column_field',
        ),
    ]
