# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0004_auto_20190814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='column_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
