# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0005_auto_20190814_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
