# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0006_indicatorprofile_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='grouped_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_profile.IndicatorProfile'),
        ),
    ]
