# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0007_indicatorprofile_grouped_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='group_remainder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
