# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0008_indicatorprofile_group_remainder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='grouped_profile',
            new_name='parent_profile',
        ),
    ]
