# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0009_auto_20190815_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
