# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0010_profile_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='disclaimer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
