# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0011_indicatorprofile_disclaimer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='universe',
            field=models.CharField(default='Population', max_length=20),
        ),
    ]
