# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-13 10:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0012_indicatorprofile_universe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='column_name',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='disclaimer_text',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='header',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='indicatorprofile',
            name='column_field',
        ),
        migrations.RemoveField(
            model_name='indicatorprofile',
            name='maximum_value',
        ),
        migrations.AddField(
            model_name='indicatorprofile',
            name='exclude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='indicatorprofile',
            name='key_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='indicatorprofile',
            name='recode',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='order_by',
            field=models.CharField(default='-total', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='percent',
            field=models.BooleanField(default=True),
        ),
    ]
