# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-15 18:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0013_auto_20190913_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='exclude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='key_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='recode',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
