# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0014_auto_20190915_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='universe',
            field=models.CharField(default='Population', max_length=50),
        ),
    ]
