# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0015_auto_20190917_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='group_remainder',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
