# Generated by Django 2.2.6 on 2019-10-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0017_indicatorprofile_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='data_context',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
