# Generated by Django 2.2.6 on 2019-10-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0018_indicatorprofile_data_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorprofile',
            old_name='data_context',
            new_name='dataset_context',
        ),
    ]
