# Generated by Django 2.2.6 on 2019-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0019_auto_20191011_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='distribution_total',
            field=models.BooleanField(default=False),
        ),
    ]
