# Generated by Django 2.2.6 on 2019-10-11 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0020_indicatorprofile_distribution_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='key_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='order_by',
            field=models.CharField(blank=True, default='-total', max_length=10, null=True),
        ),
    ]
