# Generated by Django 2.2.6 on 2019-10-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0021_auto_20191011_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
