# Generated by Django 2.2.6 on 2019-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0022_indicatorprofile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorprofile',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='indicatorprofile',
            name='universe',
        ),
    ]
