# Generated by Django 2.2.6 on 2019-10-21 06:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0023_auto_20191016_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='geo_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['country', 'province', 'district', 'municipality', 'ward', 'subplace', 'smallarea'], size=None),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='active',
            field=models.BooleanField(default=True, help_text='Should the this indicator be shown or not'),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='dataset_context',
            field=models.IntegerField(blank=True, help_text='if the dataset is outside of the census and comminuty survey datasets addd a custom date for the dataset ', null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='distribution_total',
            field=models.BooleanField(default=False, help_text='Show the distribution total as part of the headers'),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='exclude_zero',
            field=models.BooleanField(default=False, help_text='leave out 0 values'),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='field_name',
            field=models.CharField(help_text='column names from the field table', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='group_remainder',
            field=models.IntegerField(blank=True, default=20, help_text='Eg: only show top 4 languages and group the rest as other', null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='info',
            field=models.TextField(blank=True, help_text='Any details thats must be know about the dataset such as how indicators were calculated', null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='recode',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text="group values according to cetain values eg: {'R1026 - R2499':'R1k - R2.5k}", null=True),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='summary',
            field=models.CharField(help_text='description of the main value', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='title',
            field=models.CharField(help_text='name of indicator', max_length=30),
        ),
    ]
