# Generated by Django 2.2.6 on 2019-11-20 09:57

from django.db import migrations


def move_distribution_total(apps, schema_editor):
    IndicatorProfile = apps.get_model("dynamic_profile", "IndicatorProfile")
    for indicator in IndicatorProfile.objects.all():
        if indicator.distribution_total:
            indicator.header_result = "distribution_total"
            indicator.save()
        else:
            indicator.header_result = ""
            indicator.save()


class Migration(migrations.Migration):

    dependencies = [("dynamic_profile", "0028_auto_20191120_0715")]

    operations = [migrations.RunPython(move_distribution_total)]
