# Generated by Django 2.2.6 on 2019-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0029_auto_20191120_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorprofile',
            name='header_field',
            field=models.CharField(default='', max_length=20),
        ),
    ]
