# Generated by Django 2.2.6 on 2019-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0030_indicatorprofile_header_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='header_field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
