# Generated by Django 2.2.6 on 2019-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0031_auto_20191128_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='header_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicatorprofile',
            name='header_result',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
