# Generated by Django 2.2.6 on 2019-12-06 15:02

from django.db import migrations


def profile_display_order(apps, schema_editor):
    """
    We need to make sure that the display order is unique.
    """
    count = 1
    Profile = apps.get_model("dynamic_profile", "Profile")
    for profile in Profile.objects.all():
        profile.display_order = count
        count += 1
        profile.save()


class Migration(migrations.Migration):

    dependencies = [("dynamic_profile", "0033_auto_20191128_1050")]

    operations = [migrations.RunPython(profile_display_order)]
