# Generated by Django 2.2.6 on 2019-12-13 11:46

from django.db import migrations


def chart_design_width(apps, schema_editor):
    """
    Chart the chart from full-width to --full-width etc
    """
    IndicatorProfile = apps.get_model("dynamic_profile", "IndicatorProfile")
    for indicator in IndicatorProfile.objects.all():
        if indicator.chart_design == "half-width":
            indicator.chart_design = "--half-width"
            indicator.save()


class Migration(migrations.Migration):

    dependencies = [("dynamic_profile", "0036_auto_20191213_1143")]

    operations = [migrations.RunPython(chart_design_width)]
