# Generated by Django 2.2.6 on 2019-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_profile', '0038_auto_20191213_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorprofile',
            name='chart_design',
            field=models.CharField(blank=True, default='--half-width', max_length=25, null=True),
        ),
    ]
